### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by avogatro** [diodiogod/TTS-Audio-Suite#213]
**Describe the bug**
false positive detection of external IndexTTS in 
tts_audio_suite\utils\models\unified_model_interface.py", line 702

tts_audio_suite\engines\index_tts\indextts\__init__.py detected as installation

**quick temporary solution**
disable raising exception at unified_model_interface.py

**Init log**
** ComfyUI startup time: 2025-12-29 05:49:59.794
** Platform: Windows
** Python version: 3.12.10 | packaged by conda-forge | (main, Apr 10 2025, 22:08:16) [MSC v.1943 64 bit (AMD64)]
** Python executable: D:\anaconda\envs\py312\python.exe
** ComfyUI Path: E:\ComfiUI_conda
** ComfyUI Base Folder Path: E:\ComfiUI_conda
** User directory: E:\ComfiUI_conda\user
** ComfyUI-Manager config path: E:\ComfiUI_conda\user\__manager\config.ini
** Log path: E:\ComfiUI_conda\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\ComfiUI_conda\custom_nodes\rgthree-comfy
   5.9 seconds: E:\ComfiUI_conda\custom_nodes\comfyui-manager

Checkpoint files will always be loaded safely.
Total VRAM 24576 MB, total RAM 32669 MB
pytorch version: 2.7.1+cu128
Enabled fp16 accumulation.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
Using async weight offloading with 2 streams
Enabled pinned memory 14700.0
Using sage attention
Python version: 3.12.10 | packaged by conda-forge | (main, Apr 10 2025, 22:08:16) [MSC v.1943 64 bit (AMD64)]
ComfyUI version: 0.6.0
ComfyUI frontend version: 1.34.9
[Prompt Server] web root: D:\anaconda\envs\py312\Lib\site-packages\comfyui_frontend_package\static
Total VRAM 24576 MB, total RAM 32669 MB
pytorch version: 2.7.1+cu128
Enabled fp16 accumulation.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
Using async weight offloading with 2 streams
Enabled pinned memory 14700.0
Web extensions folder found at E:\ComfiUI_conda\web\extensions\ComfyLiterals
ComfyUI-GGUF: Partial torch compile only, consider updating pytorch
### Loading: ComfyUI-Impact-Pack (V8.28)
[Impact Pack] Wildcard total size (0.00 MB) is within cache limit (50.00 MB). Using full cache mode.
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Impact-Subpack (V1.3.5)
[Impact Pack/Subpack] Using folder_paths to determine whitelist path: E:\ComfiUI_conda\user\default\ComfyUI-Impact-Subpack\model-whitelist.txt
[Impact Pack/Subpack] Ensured whitelist directory exists: E:\ComfiUI_conda\user\default\ComfyUI-Impact-Subpack
[Impact Pack/Subpack] Loaded 0 model(s) from whitelist: E:\ComfiUI_conda\user\default\ComfyUI-Impact-Subpack\model-whitelist.txt
[Impact Subpack] ultralytics_bbox: E:\ComfiUI_conda\models\ultralytics\bbox
[Impact Subpack] ultralytics_segm: E:\ComfiUI_conda\models\ultralytics\segm

----------------------------------------------------------------------
[ComfyUI-Manager] NOTICE: Legacy backup exists
  - Your old Manager data was backed up to:
      E:\ComfiUI_conda\user\__manager\.legacy-manager-backup
  - Please verify and remove it when no longer needed.
----------------------------------------------------------------------

### Loading: ComfyUI-Manager (V3.39)
[ComfyUI-Manager] network_mode: public
[ComfyUI-Manager] ComfyUI per-queue preview override detected (PR #11261). Manager's preview method feature is disabled. Use ComfyUI's --preview-method CLI option or 'Settings > Execution > Live preview method'.
### ComfyUI Revision: 4431 [e4c61d75] *DETACHED | Released on '2025-12-23'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH ComfyRegistry Data: 5/116
FETCH ComfyRegistry Data: 10/116
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
FETCH ComfyRegistry Data: 15/116
FETCH ComfyRegistry Data: 20/116

[rgthree-comfy] Loaded 48 extraordinary nodes. 🎉

[rgthree-comfy] ComfyUI's new Node 2.0 rendering may be incompatible with some rgthree-comfy nodes and features, breaking some rendering as well as losing the ability to access a node's properties (a vital part of many nodes). It also appears to run MUCH more slowly spiking CPU usage and causing jankiness and unresponsiveness, especially with large workflows. Personally I am not planning to use the new Nodes 2.0 and, unfortunately, am not able to invest the time to investigate and overhaul rgthree-comfy where needed. If you have issues when Nodes 2.0 is enabled, I'd urge you to switch it off as well and join me in hoping ComfyUI is not planning to deprecate the existing, stable canvas rendering all together.

ℹ️ Critical package versions: NumPy 2.0.1, Librosa 0.11.0, Numba 0.62.1, PyTorch 2.7.1+cu128, TorchAudio 2.7.1+cu128, Transformers 4.57.1, Accelerate 1.11.0, SoundFile 0.13.1
JAX version 0.4.31 available.
APEX FusedRMSNorm not available, using native implementation
SageAttention: Using SM80+ (Ampere) FP16 kernel with pv_accum_dtype='fp32'.
FETCH ComfyRegistry Data: 25/116
======================================================================
🚀 TTS Audio Suite v4.14.36
```

**ERROR full log**
```
❌ IndexTTS-2 processor error: IndexTTS-2 dependencies not available. Error:
❌ External IndexTTS installation detected!

   Found at: E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\index_tts\indextts\__init__.py

   This conflicts with our bundled IndexTTS-2 engine and causes import errors.

   🔧 SOLUTION: Please uninstall the external version:
      pip uninstall indextts

   Then restart ComfyUI.

   Our bundled version has all required dependencies and will work perfectly.

Traceback (most recent call last):
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\models\unified_model_interface.py", line 671, in index_tts_factory
    #                     raise e
                        ^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\models\unified_model_interface.py", line 655, in index_tts_factory
    #                     raise ImportError(f"""
                        ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError:
❌ External IndexTTS installation detected!

   Found at: E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\index_tts\indextts\__init__.py

   This conflicts with our bundled IndexTTS-2 engine and causes import errors.

   🔧 SOLUTION: Please uninstall the external version:
      pip uninstall indextts

   Then restart ComfyUI.

   Our bundled version has all required dependencies and will work perfectly.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\processors\index_tts_processor.py", line 511, in process_text
    result = self.pause_processor.generate_audio_with_pauses(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\text\pause_processor.py", line 126, in generate_audio_with_pauses
    audio = tts_generate_func(content, **generation_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\processors\index_tts_processor.py", line 507, in tts_generate_with_params
    return tts_generate_func(text_content, segment_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\processors\index_tts_processor.py", line 333, in tts_generate_func
    segment_result = self.adapter.generate(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\adapters\index_tts_adapter.py", line 278, in generate
    audio = self.engine.generate(
            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\index_tts\index_tts.py", line 213, in generate
    self._ensure_model_loaded()
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\index_tts\index_tts.py", line 153, in _ensure_model_loaded
    self._tts_engine = unified_model_interface.load_model(self._model_config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\models\unified_model_interface.py", line 150, in load_model
    wrapper = tts_model_manager.load_model(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\models\comfyui_model_wrapper\model_manager.py", line 235, in load_model
    model = model_factory_func(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\models\unified_model_interface.py", line 702, in index_tts_factory
    raise ImportError(f"IndexTTS-2 dependencies not available. Error: {e}")
ImportError: IndexTTS-2 dependencies not available. Error:
❌ External IndexTTS installation detected!

   Found at: E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\index_tts\indextts\__init__.py

   This conflicts with our bundled IndexTTS-2 engine and causes import errors.

   🔧 SOLUTION: Please uninstall the external version:
      pip uninstall indextts

   Then restart ComfyUI.

   Our bundled version has all required dependencies and will work perfectly.

✅ Index_Tts generation complete. Default narrator: narrator
```


**System information**
 - OS: windows 11
 - ComfyUI type: [ conda ]
 - Python version: [3.12]

**Comment by avogatro** [comment]
l tried it is even worse with refer of non type.

`❌ IndexTTS-2 processor error: 'NoneType' object has no attribute 'infer'
Traceback (most recent call last):
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\processors\index_tts_processor.py", line 514, in process_text
    result = self.pause_processor.generate_audio_with_pauses(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\text\pause_processor.py", line 126, in generate_audio_with_pauses
    audio = tts_generate_func(content, **generation_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\processors\index_tts_processor.py", line 510, in tts_generate_with_params
    return tts_generate_func(text_content, segment_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\processors\index_tts_processor.py", line 432, in tts_generate_func
    result = self.adapter.generate(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\adapters\index_tts_adapter.py", line 281, in generate
    audio = self.engine.generate(
            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\index_tts\index_tts.py", line 333, in generate
    result = self._tts_engine.infer(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\models\comfyui_model_wrapper\base_wrapper.py", line 398, in __getattr__
    return getattr(self.model, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'infer'
❌ TTS Text generation failed: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\nodes\unified/tts_text_node.py", line 931, in generate_speech
    audio_result, chunk_info = engine_instance.process_text(
    ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)`
I want the new tag feature for emotion and speed.
I am currently trying to install separate conda env py313 and all packages.

Even if this works, have to install a specific version of python, cuda, pytorch to make this work, is not very fun...

**Comment by diodiogod** [comment]
It should be working just fine in python 3.12. Are you sure you don't have any other conflicting nodes? Can you post your full initialization comfyui log so I can check it?

**Comment by diodiogod** [comment]
You did... hum, maybe it's the anaconda environment. I have never tested with it...

**Comment by avogatro** [comment]
install.py let me try

**Comment by avogatro** [comment]
Ok I changed version to 4.15.17.
install.py show [+] Installation completed successfully!
and I restarted my job. still the same error:

`
❌ IndexTTS-2 processor error: IndexTTS-2 dependencies not available. Error:
❌ External IndexTTS installation detected!

   Found at: E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\index_tts\indextts\__init__.py

   This conflicts with our bundled IndexTTS-2 engine and causes import errors.

   🔧 SOLUTION: Please uninstall the external version:
      pip uninstall indextts

   Then restart ComfyUI.

   Our bundled version has all required dependencies and will work perfectly.

Traceback (most recent call last):
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\models\unified_model_interface.py", line 696, in index_tts_factory
    raise e
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\models\unified_model_interface.py", line 680, in index_tts_factory
    raise ImportError(f"""
ImportError:
❌ External IndexTTS installation detected!

   Found at: E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\index_tts\indextts\__init__.py

   This conflicts with our bundled IndexTTS-2 engine and causes import errors.

   🔧 SOLUTION: Please uninstall the external version:
      pip uninstall indextts

   Then restart ComfyUI.

   Our bundled version has all required dependencies and will work perfectly.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\processors\index_tts_processor.py", line 514, in process_text
    result = self.pause_processor.generate_audio_with_pauses(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\text\pause_processor.py", line 126, in generate_audio_with_pauses
    audio = tts_generate_func(content, **generation_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\processors\index_tts_processor.py", line 510, in tts_generate_with_params
    return tts_generate_func(text_content, segment_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\processors\index_tts_processor.py", line 432, in tts_generate_func
    result = self.adapter.generate(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\adapters\index_tts_adapter.py", line 281, in generate
    audio = self.engine.generate(
            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\index_tts\index_tts.py", line 216, in generate
    self._ensure_model_loaded()
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\index_tts\index_tts.py", line 156, in _ensure_model_loaded
    self._tts_engine = unified_model_interface.load_model(self._model_config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\models\unified_model_interface.py", line 156, in load_model
    wrapper = tts_model_manager.load_model(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\models\comfyui_model_wrapper\model_manager.py", line 253, in load_model
    model = model_factory_func(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\utils\models\unified_model_interface.py", line 728, in index_tts_factory
    raise ImportError(f"IndexTTS-2 dependencies not available. Error: {e}")
ImportError: IndexTTS-2 dependencies not available. Error:
❌ External IndexTTS installation detected!

   Found at: E:\ComfiUI_conda\custom_nodes\tts_audio_suite\engines\index_tts\indextts\__init__.py

   This conflicts with our bundled IndexTTS-2 engine and causes import errors.

   🔧 SOLUTION: Please uninstall the external version:
      pip uninstall indextts

   Then restart ComfyUI.

   Our bundled version has all required dependencies and will work perfectly.

❌ TTS Text generation failed: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "E:\ComfiUI_conda\custom_nodes\tts_audio_suite\nodes\unified/tts_text_node.py", line 931, in generate_speech
    audio_result, chunk_info = engine_instance.process_text(
    ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
Prompt executed in 5.45 seconds
`

**Comment by avogatro** [comment]
I use conda to create python 3.13 env, switched now to the nightly build.

**Comment by diodiogod** [comment]
Closing this as resolved for the original report scope.

The initial bug here was a false-positive \"external IndexTTS installation detected\" check when the bundled `indextts` path contained keywords like `conda`. That detection logic was changed to path-based bundled-module validation, and this specific conflict is no longer tracked as an active bug in current versions.

This thread later mixed in separate issues (dependency/install gaps, Python 3.13 + Transformers 5 compatibility, and downstream `not enough values to unpack` failures). Those need isolated reports to debug properly.

If you still reproduce problems on the latest TTS Audio Suite version, please open a new issue with:
- exact suite version
- OS / Python / PyTorch / Transformers versions
- full startup log + full runtime traceback
- minimal reproducible workflow JSON
